name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      env: 
        my_secret: ${{ secrets.MY_SECRET }}
      run: echo $my_secret > testfile.txt
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: homework
        path: testfile.txt
